import { at, labelOf, line, meaningOf, type Ctx } from "@/lib/context"
import type { Material } from "@/lib/types"

export function buildPlans(ctx: Ctx): Material[] {
  const a = at(ctx, 0)
  const b = at(ctx, 1)
  const c = at(ctx, 2)
  const d = at(ctx, 3)
  const items = [a, b, c, d, at(ctx, 4), at(ctx, 5)]
  const shown = items.map((item) => (item.gloss ? `${item.term} (${item.gloss})` : item.term))

  return [
    {
      id: "bell-ringer",
      title: "Bell-ringer Can-Do",
      hook: "Three quiet checks on the board before anyone is asked to talk.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Communication"],
      canDo: ctx.canDos.interpretive,
      minutes: 3,
      spotlight: "quiet",
      playable: false,
      quick: true,
      xp: 0,
      whySafe: "The period opens on paper. The first voice of the day is not a solo.",
      steps: [
        "Project the three prompts as students walk in. No greeting drill yet.",
        "They write. You circulate and read over shoulders.",
        "Chorus the answer key once, from the Chorus Countdown, instead of calling a name.",
      ],
      support: "Leave yesterday's word bank in the corner of the slide.",
      stretch: "A fourth prompt: write a question you could ask about the topic.",
      handout: [
        {
          kind: "list",
          title: "On the board",
          items: [
            `1. Circle the word that means “${a.gloss || labelOf(a)}”:  ${shown.slice(0, 3).join("   /   ")}`,
            `2. Match: ${line(ctx, "want", 0)}  →  ${meaningOf(ctx, "want", 0)}`,
            `3. Finish the line: ${ctx.pack.framed ? line(ctx, "howMuch", 1).replace(b.term, "______") : `______ (${meaningOf(ctx, "howMuch", 1)})`}`,
          ],
        },
      ],
    },
    {
      id: "info-gap",
      title: "Info-gap Booth",
      hook: "Each partner holds half the facts. They whisper until both cards are full.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.canDos.interpersonal,
      minutes: 8,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "The noise of every pair at once is the camouflage. Nobody reports to the class.",
      steps: [
        "Cut the table into A and B. Partners may not show the paper.",
        `A asks with: ${line(ctx, "howMuch", 0)}  B answers with a number plus the item.`,
        "They swap roles after four items. Then both papers go in the folder, not on the board.",
      ],
      support: `Print the question frame at the top of both cards: ${line(ctx, "howMuch", 0)}`,
      stretch: "B may say the item is unavailable and offer a different one.",
      handout: [
        {
          kind: "table",
          title: "A has the list. B has the prices.",
          columns: ["Student A asks about", "Student B answers"],
          rows: [
            [labelOf(a), "3"],
            [labelOf(b), "5"],
            [labelOf(c), "8"],
            [labelOf(d), "12"],
          ],
        },
        { kind: "note", text: "Digits are fine if target-language numbers are not solid yet. Say so out loud so nobody apologizes." },
      ],
    },
    {
      id: "prompt-jar",
      title: "Anonymous Prompt Jar",
      hook: "The replacement for hot seat. The prompt is public. The speaker is not.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.canDos.interpersonal,
      minutes: 7,
      spotlight: "chorus",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "You never call a name. Either the chorus answers, or you read unsigned slips.",
      steps: [
        "Cut the prompts into the jar. Draw one.",
        "Twenty seconds of quiet prep. Notes allowed.",
        "On three, everyone says an answer together. If that is too loud for the room, they write the line with no name and you read three slips without guessing who wrote them.",
        "Praise a phrase you heard. Do not praise a person.",
      ],
      support: "Flash the model line for that prompt before the countdown.",
      stretch: "Second draw: notes closed.",
      handout: [
        {
          kind: "list",
          title: "Jar slips",
          items: [
            `Say you want ${labelOf(a)}.`,
            `Ask the price of ${labelOf(b)}.`,
            `Say you like ${labelOf(c)}.`,
            `Say there is no ${labelOf(d)}.`,
            "Ask someone to repeat.",
            "Say goodbye and thank them.",
            `Ask where ${labelOf(a)} is.`,
            `Give a reason using “${ctx.pack.because}”.`,
          ],
        },
      ],
    },
    {
      id: "error-hospital",
      title: "Error Hospital",
      hook: "One line on the board is hurt. Pairs whisper the fix. The class says only the healthy line.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Communication"],
      canDo: ctx.canDos.interpretive,
      minutes: 6,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "They diagnose a sentence, not a classmate. The chorus speaks the repair.",
      steps: [
        "Write all four lines. Do not mark the broken one.",
        "Pairs whisper which line fails and how they would say it.",
        "On your cue, the class says only the repaired line together.",
      ],
      support: "Tell them the pattern you are watching: " + ctx.grammar,
      stretch: "They write a fifth line that uses the pattern with a new item.",
      handout: [
        {
          kind: "list",
          title: "Board lines (key underneath)",
          items: [
            line(ctx, "want", 0),
            broken(line(ctx, "howMuch", 1)),
            line(ctx, "like", 2),
            `${line(ctx, "have", 3)} ???`,
            `Key: the price line should be “${line(ctx, "howMuch", 1)}”. The last line should drop the question marks: “${line(ctx, "have", 3)}”.`,
          ],
        },
      ],
    },
    {
      id: "listening-cloze",
      title: "Listening Cloze",
      hook: "You read. They fill. No student voice required.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Communication"],
      canDo: ctx.canDos.interpretive,
      minutes: 6,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Interpretive mode is the job. Speaking can wait until the words are already in their ears.",
      steps: [
        "Read each full sentence twice, at a normal pace, then once slower.",
        "They write the missing item.",
        "Show the key. They check their own paper.",
      ],
      support: "Give a word bank of the four missing items at the top.",
      stretch: "Third listen: they write one extra word they heard besides the blank.",
      handout: [
        {
          kind: "list",
          title: "Student blanks / your script",
          items: [
            `I want ______.   You read: ${line(ctx, "want", 0)}`,
            `How much is ______?   You read: ${line(ctx, "howMuch", 1)}`,
            `I like ______.   You read: ${line(ctx, "like", 2)}`,
            `Where is ______?   You read: ${line(ctx, "where", 3)}`,
          ],
        },
      ],
    },
    {
      id: "comic-strip",
      title: "Four-panel Comic",
      hook: "They draw the scene and caption it. Speaking is a whisper to one partner, later, maybe.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication", "Cultures"],
      canDo: ctx.canDos.presentational,
      minutes: 10,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "The presentational product is the page. A gallery walk can happen with no one standing up front.",
      steps: [
        "Four boxes. Stick figures are the standard, not a bonus.",
        "Each box gets the caption from the handout, or their own line if they have one.",
        "Optional closer: whisper the comic to one partner. Decline is a complete choice.",
      ],
      support: "Captions printed on the sheet. They only draw.",
      stretch: "They replace one caption with a line you did not supply.",
      handout: [
        {
          kind: "list",
          title: "Panels",
          items: [
            `1. Arrive.  ${ctx.pack.hello}`,
            `2. Ask.  ${line(ctx, "want", 0)}`,
            `3. The snag.  ${ctx.pack.tooMuch}`,
            `4. Leave.  ${ctx.pack.thanks}. ${ctx.pack.goodbye}.`,
          ],
        },
        { kind: "note", text: ctx.culture },
      ],
    },
    {
      id: "gallery-walk",
      title: "Gallery Walk Captions",
      hook: "Papers on the wall. Sticky notes. You read two unsigned notes at the end.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication"],
      canDo: ctx.canDos.presentational,
      minutes: 8,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Presentational mode does not require a standing performance. The wall holds the work.",
      steps: [
        "Post the four captions around the room with a blank under each.",
        "Students stick one response under a caption: a check, a question, or a new item.",
        "You read two stickies with no names. Then you stop.",
      ],
      support: "A frame on the sticky: “Me gusta ______.” or the equivalent you teach.",
      stretch: "One sticky must be a question, not a statement.",
      handout: [
        {
          kind: "list",
          title: "Post these",
          items: [line(ctx, "want", 0), line(ctx, "howMuch", 1), line(ctx, "like", 2), line(ctx, "problem", 3)],
        },
      ],
    },
    {
      id: "stations",
      title: "Four-station Circuit",
      hook: "Twenty minutes, four stops, no whole-class speaking turn.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.objective || ctx.canDos.interpersonal,
      minutes: 20,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Rotation means nobody is the center of the room. Each stop has a product you can see without a performance.",
      steps: [
        "Stations: Word Sprint on paper, Whisper Cards, Four-panel Comic, Pip's Private Mission on two devices.",
        "Four minutes each. A chime, not your voice calling names, moves them.",
        "You stay at the comic station and talk only to students who wave you over.",
      ],
      support: "The mission station has the model lines face up.",
      stretch: "A fifth folder labeled “one more detail” for anyone who finishes a station early.",
      handout: [
        {
          kind: "list",
          title: "Station signs",
          items: [
            "1. Word Sprint — pencil, no talking",
            "2. Whisper Cards — one partner only",
            "3. Comic — draw, caption, stay seated",
            "4. Pip — headphones or a whisper to the screen",
          ],
        },
      ],
    },
    {
      id: "culture-snapshot",
      title: "Culture Snapshot",
      hook: "One practice, the perspective under it, then a whispered comparison.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Cultures", "Comparisons"],
      canDo: `I can identify one way people handle ${ctx.topic} and say whether it matches what I know.`,
      minutes: 7,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "The comparison is whispered. Nobody is asked to represent a whole culture out loud.",
      steps: [
        "Read the snapshot once. Students underline the action people take first.",
        "Pairs whisper: same, different, or not sure — and one target-language line they would actually use.",
        "Collect the “not sure” questions on a sticky. Those become tomorrow's interpretive text, not today's interrogation.",
      ],
      support: "Sentence frame: Same for me / Different for me / I'm not sure.",
      stretch: "They add a product (an object) that goes with the practice.",
      handout: [
        { kind: "note", text: ctx.culture },
        {
          kind: "list",
          title: "Whisper one of these",
          items: [ctx.pack.hello, line(ctx, "want", 0), ctx.pack.repair],
        },
      ],
    },
    {
      id: "compare-it",
      title: "Compare the Line",
      hook: "Set the target-language line next to the way they would say it in a language they already own.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Comparisons"],
      canDo: `I can compare how I ask for something in ${ctx.lesson.language} with how I ask in another language I know.`,
      minutes: 6,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "The comparison is written. Sharing is a voluntary sticky note.",
      steps: [
        `Column A: ${line(ctx, "howMuch", 0)}`,
        "Column B: the same job in English or another language they actually use.",
        "They star one thing that is different (word order, a title, a greeting first). No speeches.",
      ],
      support: "You model the star with your own two languages, including a language you speak less well.",
      stretch: "They do a second pair: the repair line.",
      handout: [
        {
          kind: "table",
          title: "Two ways to do the same job",
          columns: [ctx.lesson.language, "A language I already use"],
          rows: [
            [line(ctx, "howMuch", 0), ""],
            [ctx.pack.hello, ""],
            [ctx.pack.repair, ""],
          ],
        },
      ],
    },
    {
      id: "community-quest",
      title: "Community Quest",
      hook: "One fact from outside the room. The retell in class is a single private line.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communities"],
      canDo: `I can bring back one real detail about ${ctx.topic} and say one practiced line about it.`,
      minutes: 8,
      spotlight: "private",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Homework can be in English. The in-class language is said to Pip or a partner, not from the front.",
      steps: [
        "Ask one person outside class, or one reliable source, a single question about the topic. English is allowed.",
        "Bring back one fact, written.",
        `In class, say only this shape of line to Pip or a partner: ${line(ctx, "have", 0)}`,
      ],
      support: "If they cannot ask anyone, the fact can come from a label, a menu, or a school poster.",
      stretch: "They add where the fact came from, in a second sentence.",
      handout: [
        {
          kind: "list",
          title: "Bring this back",
          items: [
            `Question I asked (any language): something about ${ctx.topic}`,
            "Fact I heard:",
            `Line I can say: ${line(ctx, "have", 0)}`,
          ],
        },
      ],
    },
    {
      id: "connection",
      title: "Other-class Connection",
      hook: "One move this topic shares with another subject they already take.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Connections"],
      canDo: `I can use what I know from another class to make sense of ${ctx.topic}.`,
      minutes: 5,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "They write the link. You read a few papers. No one is the spokesperson.",
      steps: [
        connectionStep(ctx),
        "They write the link in English and one target-language word that belongs in it.",
        "You sort the papers into a pile for tomorrow rather than narrating them now.",
      ],
      support: "Offer two subjects to choose from: math, and whatever this topic naturally touches.",
      stretch: "They add a number, a date, or a measurement from that other class.",
      handout: [
        {
          kind: "note",
          text: connectionStep(ctx),
        },
      ],
    },
    {
      id: "taboo",
      title: "Password, Not a Performance",
      hook: "Partner A gives the meaning. Partner B says the word. The card never faces the class.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.canDos.interpersonal,
      minutes: 6,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "It has the feel of a game and the audience of one person.",
      steps: [
        "A says the English or points. A may not say the target word.",
        "B says the target word. Then they swap.",
        "A point only if you need scorekeeping: one point per word, no running class total on the board.",
      ],
      support: "A may show the first letter.",
      stretch: "B must say the word inside a full frame, not alone.",
      handout: [
        {
          kind: "table",
          title: "Password cards",
          columns: ["You may say", "Your partner must say"],
          rows: items.slice(0, 6).map((item) => [item.gloss || "act it out", item.term]),
        },
      ],
    },
    {
      id: "bingo",
      title: "Interview Bingo",
      hook: "They ask until they hear four items. The board is the conversation.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.canDos.interpersonal,
      minutes: 8,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "The game ends when the card is full, not when someone performs the best interview.",
      steps: [
        `Teach one question and leave it on the board: ${line(ctx, "questionLike", 0)}`,
        "They ask a partner, mark the item they hear, then either partner may rotate.",
        "Four marks ends it. Winners sit down. There is no playoff.",
      ],
      support: "Answers can be the single item. A full sentence is welcome, not required, at Novice.",
      stretch: "The answer must include because plus a reason.",
      handout: [
        {
          kind: "list",
          title: "Squares",
          items: shown.slice(0, 6).concat([ctx.pack.hello, ctx.pack.thanks]),
        },
      ],
    },
    {
      id: "chant",
      title: "Four-beat Chant",
      hook: "Rhythm carries the line. Dropped words get picked up by the beat, not by a stare.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication"],
      canDo: ctx.canDos.presentational,
      minutes: 4,
      spotlight: "chorus",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Choral repetition with a beat is shared air. You clap, you do not conduct solos.",
      steps: [
        "Clap four beats. Put one line on each beat.",
        "All voices, two rounds.",
        "Round three is optional and still all voices. Then you stop while it still feels like a game.",
      ],
      support: "Keep the text projected the whole time.",
      stretch: "They swap in a different item on beat two and the class follows.",
      handout: [
        {
          kind: "list",
          title: "The chant",
          items: [ctx.pack.hello, line(ctx, "want", 0), line(ctx, "howMuch", 1), `${ctx.pack.thanks}.`],
        },
      ],
    },
    {
      id: "emoji-retell",
      title: "Emoji Retell",
      hook: "Four pictures, four lines, then the words get covered.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication"],
      canDo: ctx.canDos.presentational,
      minutes: 7,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Memory is propped up by the pictures. The retell is a whisper, and only if they want it.",
      steps: [
        "They write the line under each emoji.",
        "They fold the words under. Looking only at the emoji, they whisper the four lines to a partner.",
        "Partner may unfold one line if the whisper stalls.",
      ],
      support: "Lines are printed. They copy, then cover.",
      stretch: "They add a fifth emoji of their own and a line you did not write.",
      handout: [
        {
          kind: "list",
          title: "Emoji, then line",
          items: [
            `👋  ${ctx.pack.hello}`,
            `⭐  ${line(ctx, "want", 0)}`,
            `💸  ${line(ctx, "howMuch", 1)}`,
            `🙂  ${ctx.pack.thanks}`,
          ],
        },
      ],
    },
    {
      id: "storyboard",
      title: "Storyboard Booth",
      hook: "Same four beats as the comic, told in a booth. No playback for the class.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication"],
      canDo: ctx.canDos.presentational,
      minutes: 8,
      spotlight: "private",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "A voice memo on their own phone, or a pass through Pip, is evidence enough. Ask before you ever collect audio.",
      steps: [
        "They order the four beats on a strip of paper.",
        "They tell the strip to Pip in the arcade, or into a voice memo they do not have to send.",
        "The exit product you see is the ordered strip, not the recording.",
      ],
      support: "They may read the strip. Reading a prepared line is presentational practice.",
      stretch: "They insert one complication beat before the thank-you.",
      handout: [
        {
          kind: "list",
          title: "Beats to order",
          items: [ctx.pack.hello, line(ctx, "want", 0), ctx.pack.tooMuch, `${ctx.pack.thanks}. ${ctx.pack.goodbye}.`],
        },
        { kind: "note", text: "Do not require students to play a recording for the class." },
      ],
    },
    {
      id: "question-ladder",
      title: "Question Ladder",
      hook: "Three rungs, from “which word” to “why.” They climb on paper.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Communication"],
      canDo: ctx.canDos.interpretive,
      minutes: 6,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "You can see how far the ladder went without asking anyone to answer live.",
      steps: [
        "Rung 1 is recognition. Rung 2 is the gist of a line. Rung 3 is a reason.",
        "Stop the class at the rung that matches the band. Higher rungs are optional.",
        "Chorus the sample answer only if you want the sound in the room.",
      ],
      support: `Novice classes stop after rung 2. Sample answer: ${line(ctx, "like", 0)}`,
      stretch: "Rung 3 asks for because. Intermediate and above.",
      handout: [
        {
          kind: "list",
          title: "Rungs",
          items: [
            `1. Underline ${a.term} in this line: ${line(ctx, "want", 0)}`,
            `2. What is the person trying to do? Sample: ${meaningOf(ctx, "want", 0)}`,
            `3. Why that item? Sample: ${line(ctx, "like", 0)}, ${ctx.pack.because}…`,
          ],
        },
      ],
    },
    {
      id: "self-check",
      title: "Can-do Self Check",
      hook: "They mark the truth. You do not turn it into a hand-raise.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication"],
      canDo: ctx.objective || ctx.canDos.presentational,
      minutes: 3,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Confidence stays on the paper. The “not yet” option names a word they want tomorrow, which gives you a plan.",
      steps: [
        "Read the four choices. They circle one.",
        "If they circle “not yet,” they write the word they want on the line.",
        "You collect. You do not sort students into groups in front of them.",
      ],
      support: "Model circling “with the word bank” yourself, about a language you are learning.",
      stretch: "Students on the top rung write the detail they could add.",
      handout: [
        {
          kind: "list",
          title: "Circle one",
          items: [
            `I can handle ${ctx.topic} with a word bank in front of me.`,
            "I can say or write one sentence.",
            "I can add a detail or a question.",
            "Not yet. The word I want tomorrow is: __________",
          ],
        },
      ],
    },
    {
      id: "rubric",
      title: "Formative Rubric",
      hook: "A way to listen during pair work without turning practice into a test.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.objective || ctx.canDos.interpersonal,
      minutes: 5,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "You rate the language you overhear, on a clipboard, and you tell the class the pattern you noticed, not the names.",
      steps: [
        `Text type you are listening for at this band: ${ctx.textType}.`,
        "Mark starting, at level, or stretching for the pair, not for a ranked individual speech.",
        "Feedback to the room is one phrase you want everyone to steal tomorrow.",
      ],
      support: "At Novice, a memorized line that does the job is “at level,” not a failure to be creative.",
      stretch: "Stretching means they added a detail, a question, or a repair that was not on the card.",
      handout: [
        {
          kind: "list",
          title: "While they work",
          items: [
            `Starting — words come only with a prompt, and the partner supplies the line. The job of the task barely happens.`,
            `At level — ${ctx.textType.toLowerCase()} gets the job done for ${ctx.topic}.`,
            "Stretching — they add a detail, ask something, or repair a misunderstanding without a new script.",
            "Say back to the class: one phrase worth stealing. No names.",
          ],
        },
      ],
    },
    {
      id: "stretch-card",
      title: "Fast-finisher Detail",
      hook: "One more detail, not a second full task that makes the others feel slow.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication"],
      canDo: ctx.canDos.presentational,
      minutes: 3,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Early finishers stay in their seat with a card. They are not asked to demo for the people still working.",
      steps: [
        "Hand the card only when a student is actually done, not as a public challenge.",
        "They add a price, a reason, or a time to a line they already built.",
        "The card stays in the notebook.",
      ],
      support: "The frame is printed. They fill one blank.",
      stretch: "Two details, still one sentence if the band is Intermediate.",
      handout: [
        {
          kind: "list",
          title: "Add one",
          items: [
            `${line(ctx, "want", 0)}, ${ctx.pack.because} ______.`,
            `${line(ctx, "howMuch", 1)}  →  ______.`,
            `${line(ctx, "yesterday", 2)}.`,
          ],
        },
      ],
    },
    {
      id: "word-bank",
      title: "Leave-up Word Bank",
      hook: "The bank stays projected so memory is not the price of speaking.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Communication"],
      canDo: ctx.canDos.interpretive,
      minutes: 2,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "A visible bank tells the class that forgetting a word is ordinary, not a public event.",
      steps: [
        "Put the bank up before the first speaking move and leave it there.",
        "Sort it into greetings, items, and repairs so the eye can find a word fast.",
        "When you take it down, say you are taking it down. Do not vanish it mid-turn.",
      ],
      support: "This is the support. It is not a crutch you apologize for.",
      stretch: "Cover the English column for the last activity only.",
      handout: [
        {
          kind: "table",
          title: "Project this",
          columns: ["Class language", "Job it does"],
          rows: [
            [ctx.pack.hello, "greet"],
            [line(ctx, "want", 0), meaningOf(ctx, "want", 0)],
            [line(ctx, "howMuch", 1), meaningOf(ctx, "howMuch", 1)],
            [ctx.pack.repair, "ask for a repeat"],
            [ctx.pack.tooMuch, "react to a price"],
            [ctx.pack.goodbye, "close"],
          ],
        },
      ],
    },
    {
      id: "homework",
      title: "Homework Micro-quest",
      hook: "Eight minutes at home with Pip. The evidence is a rank name, not a recording.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communities", "Communication"],
      canDo: ctx.canDos.interpersonal,
      minutes: 8,
      spotlight: "private",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Home practice on a screen removes the class audience entirely. They report the rank, which is a game word, not a score out loud.",
      steps: [
        "Assign Pip's Private Mission from the student arcade.",
        "Tomorrow they write their rank name on a slip: Ticket stub, Regular, High score, House player, or Closing crew.",
        "You do not ask anyone to replay the mission live.",
      ],
      support: "Typed lines count. Say that in the assignment.",
      stretch: "If they already finished Pip, they play one mask.",
      handout: [
        {
          kind: "note",
          text: `Open the student arcade for “${ctx.lesson.title || ctx.topic}”, play Pip's Private Mission, and bring the rank name. Speaking into the mic is optional. Nothing is uploaded.`,
        },
      ],
    },
    {
      id: "transaction",
      title: "Transaction, in Masks",
      hook: "Customer and vendor, ninety seconds, every pair at once.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication", "Cultures"],
      canDo: ctx.canDos.interpersonal,
      minutes: 8,
      spotlight: "mask",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Roles make it fiction, and a loud room means no pair is audible at the next desk.",
      steps: [
        "A is the customer, B is the vendor. Scripts face up the first time.",
        "Ninety seconds, then they swap the masks.",
        `If you want one cultural constraint, use this: ${ctx.culture}`,
      ],
      support: "Scripts stay up. Fluency is not the goal of the first pass.",
      stretch: "Second pass, vendor closes the script. Customer may keep it.",
      handout: [
        {
          kind: "table",
          title: "Masks",
          columns: ["Customer", "Vendor"],
          rows: [
            [ctx.pack.hello, ctx.pack.hello],
            [line(ctx, "want", 0), ctx.pack.yes],
            [line(ctx, "howMuch", 0), "3"],
            [ctx.pack.tooMuch, line(ctx, "invite", 1)],
            [`${ctx.pack.thanks}. ${ctx.pack.goodbye}.`, ctx.pack.goodbye],
          ],
        },
      ],
    },
    {
      id: "two-truths",
      title: "Two-line Booth",
      hook: "One line that fits them, one line that does not. Pip does not know which.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communication"],
      canDo: ctx.canDos.presentational,
      minutes: 6,
      spotlight: "private",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Guessing, if it happens, is with one partner who opted in. The class never hears the personal line.",
      steps: [
        `They write two lines with ${ctx.grammar}. One is true for them, one is not.`,
        "They read both to Pip, or leave them on the paper.",
        "Optional: a partner guesses in a whisper. Either student can pass.",
      ],
      support: `Frames: ${line(ctx, "like", 0)}  /  ${line(ctx, "have", 1)}`,
      stretch: "Add a reason to the true line only.",
      handout: [
        {
          kind: "list",
          title: "Write both",
          items: [
            `Line A: ${line(ctx, "like", 0)}`,
            `Line B: ${line(ctx, "have", 1)}`,
            "Mark the true one with a dot on the back.",
          ],
        },
      ],
    },
    {
      id: "postcard",
      title: "Postcard Home",
      hook: "Four sentences to a real person. Read it to Pip if reading it to the person feels like too much.",
      kind: "plan",
      mode: "Presentational",
      cs: ["Communities", "Communication"],
      canDo: ctx.canDos.presentational,
      minutes: 10,
      spotlight: "private",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "A postcard is presentational and still private. Delivery is the student's choice.",
      steps: [
        "They write four sentences using four different items or functions.",
        "They read it once to Pip or to someone at home.",
        "You check the writing. You do not host a reading.",
      ],
      support: "Give all four frames on the card so the writing cannot stall on memory.",
      stretch: "They replace frame four with a question to the reader.",
      handout: [
        {
          kind: "list",
          title: "Frames",
          items: [ctx.pack.hello, line(ctx, "have", 0), line(ctx, "like", 1), `${ctx.pack.goodbye}`],
        },
      ],
    },
    {
      id: "spot-pattern",
      title: "Spot the Pattern",
      hook: "Four lines, one pattern, then they write a fifth with a new item.",
      kind: "plan",
      mode: "Interpretive",
      cs: ["Communication", "Comparisons"],
      canDo: `I can find the pattern in practiced lines about ${ctx.topic} and reuse it.`,
      minutes: 6,
      spotlight: "quiet",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Grammar stays inside a task, on paper, where a wrong underline is cheap.",
      steps: [
        `Name the pattern in student language: ${ctx.grammar}.`,
        "They underline the piece that repeats.",
        "They write one new line with an item from the bank that the four lines did not use.",
      ],
      support: "Underline the first line yourself, slowly, narrating the choice.",
      stretch: "They write a question using the same pattern.",
      handout: [
        {
          kind: "list",
          title: "Underline what repeats",
          items: [line(ctx, "want", 0), line(ctx, "want", 1), line(ctx, "want", 2), line(ctx, "want", 3), "Mine:"],
        },
      ],
    },
    {
      id: "choice-cards",
      title: "Choice Cards",
      hook: "Two versions of the same job. The student picks the card. You do not assign the “low” one in public.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.canDos.interpersonal,
      minutes: 6,
      spotlight: "pair",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "Choice is private. Both cards finish in a whisper to a partner, so the versions are not a status display.",
      steps: [
        "Put both cards in a folder. Students take one without showing you.",
        "They complete it, then whisper the result to a partner who may have the other card.",
        "Partner's only job is to say whether the job got done, not to correct every form.",
      ],
      support: "Card A is the model plus a blank. That is a full task.",
      stretch: "Card B has the complication and no model.",
      handout: [
        {
          kind: "table",
          title: "Same job, two doors",
          columns: ["Card A", "Card B"],
          rows: [
            [
              `Model: ${line(ctx, "want", 0)}. Your turn: say you want a different item.`,
              `There is no ${labelOf(a)}. Ask for something else, then ask the price. No model on this card.`,
            ],
          ],
        },
      ],
    },
    {
      id: "campaign",
      title: "Arcade Campaign Path",
      hook: "The order the student arcade already uses, if you want the same arc on a plan book page.",
      kind: "plan",
      mode: "Interpersonal",
      cs: ["Communication"],
      canDo: ctx.objective || ctx.canDos.interpersonal,
      minutes: 15,
      spotlight: "private",
      playable: false,
      quick: false,
      xp: 0,
      whySafe: "It starts with recognition and only asks for an open line after the words have already been in their hands.",
      steps: [
        "Open the student arcade and let them move down the path, or run the stops yourself in this order.",
        "Word Sprint, Line Forge, Chorus, Whisper Cards, Mask Quest, Pip's Private Mission, Exit Ticket.",
        "A 15-minute day can stop after Chorus and send Pip home as the micro-quest.",
      ],
      support: "Tell them the mic is optional on every stop.",
      stretch: "House player rank or higher: they replay one mask with the word bank off.",
      handout: [
        {
          kind: "list",
          title: "Path",
          items: [
            "1. Word Sprint — quiet",
            "2. Line Forge — build, then a private say",
            "3. Chorus Countdown — all voices",
            "4. Whisper Cards — one partner",
            "5. Mask Quest — the character talks",
            "6. Pip's Private Mission — open line, still private",
            "7. Exit Ticket — include the pulse",
          ],
        },
      ],
    },
  ]
}

function broken(lineText: string) {
  const parts = lineText.split(/\s+/).filter(Boolean)
  if (parts.length < 3) return `${lineText} ?`
  return [parts[parts.length - 1], ...parts.slice(0, -1)].join(" ")
}

function connectionStep(ctx: Ctx) {
  const topic = ctx.topic.toLowerCase()
  if (/market|food|buy|shop|store|price|menu|restaurant/.test(topic)) {
    return `Prices pull in math. Have students attach a number they already know to ${at(ctx, 0).term}.`
  }
  if (/school|class|week|schedule|day/.test(topic)) {
    return `This is also a calendar. Put the days in order before anyone speaks, then name one thing that happens on ${at(ctx, 0).term}.`
  }
  if (/meet|greet|name|introduc|hello/.test(topic)) {
    return "This is the same move as walking into a new club or a lab: one line for who you are, then one question."
  }
  return `Name another class that already touches ${ctx.topic}. Students add one fact from that class, in the target language if they can.`
}
